import { writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';

import { DEFAULT_BACKTEST_OPTIONS, runBacktest } from '@civora/forecasting';
import {
  DEMO_HISTORY_FACILITIES_PER_REGION,
  DEMO_NETWORK_OPTIONS,
  DEMO_SEED,
  buildNetwork,
  historySample,
  simulateNetwork,
} from '@civora/simulator';
import type { NetworkOptions } from '@civora/simulator';

import { buildScoredSeries } from './dataset-series';
import { renderEvaluationReport } from './evaluation-report';
import { comparePolicies, pairsFromSimulation } from './policy';

/**
 * `pnpm forecast:backtest` — score the forecasting engine and write the report.
 *
 * The command exists so that every forecasting number shown anywhere in this
 * project traces to one reproducible run with a published seed. A figure in a
 * pitch deck that nobody can regenerate is a claim; this is the thing that turns
 * it into evidence.
 */

const USAGE = `
Score the forecasting engine against the generated dataset and write a report.

  pnpm forecast:backtest [options]

Options
  --profile <demo|national>   network coverage (default: demo)
  --seed <value>              generation seed (default: ${DEMO_SEED})
  --horizon <days>            forecast horizon (default: ${String(DEFAULT_BACKTEST_OPTIONS.horizonDays)})
  --stride <days>             days between origins (default: ${String(DEFAULT_BACKTEST_OPTIONS.strideDays)})
  --origins <n>               origins per series (default: ${String(DEFAULT_BACKTEST_OPTIONS.maxOriginsPerSeries)})
  --out <path>                where to write the report (default: docs/EVALUATION.md)
  --stdout                    print the report instead of writing it
  --help                      print this message

The report is generated from the data, so it cannot drift from the code that
produced it. Everything in the dataset is simulated.
`.trim();

class UsageError extends Error {}

interface Options {
  readonly profile: 'demo' | 'national';
  readonly seed: string;
  readonly horizonDays: number;
  readonly strideDays: number;
  readonly origins: number;
  readonly out: string;
  readonly toStdout: boolean;
}

const KNOWN_FLAGS = new Set(['--profile', '--seed', '--horizon', '--stride', '--origins', '--out']);

function parseArguments(argv: readonly string[]): Options {
  const flags = new Map<string, string>();

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === undefined) {
      continue;
    }
    if (argument === '--stdout') {
      flags.set('--stdout', 'yes');
      continue;
    }
    if (!argument.startsWith('--')) {
      throw new UsageError(`unexpected argument "${argument}"`);
    }
    const value = argv[index + 1];
    if (value === undefined || value.startsWith('--')) {
      throw new UsageError(`${argument} needs a value`);
    }
    flags.set(argument, value);
    index += 1;
  }

  const unknown = [...flags.keys()].filter((flag) => flag !== '--stdout' && !KNOWN_FLAGS.has(flag));
  if (unknown.length > 0) {
    throw new UsageError(`unknown option ${unknown.join(', ')}`);
  }

  const profile = flags.get('--profile') ?? 'demo';
  if (profile !== 'demo' && profile !== 'national') {
    throw new UsageError(`--profile must be demo or national, not "${profile}"`);
  }

  const whole = (flag: string, fallback: number): number => {
    const raw = flags.get(flag);
    if (raw === undefined) {
      return fallback;
    }
    const value = Number(raw);
    if (!Number.isInteger(value) || value < 1) {
      throw new UsageError(`${flag} must be a whole number of at least one`);
    }
    return value;
  };

  return {
    profile,
    seed: flags.get('--seed') ?? DEMO_SEED,
    horizonDays: whole('--horizon', DEFAULT_BACKTEST_OPTIONS.horizonDays),
    strideDays: whole('--stride', DEFAULT_BACKTEST_OPTIONS.strideDays),
    origins: whole('--origins', DEFAULT_BACKTEST_OPTIONS.maxOriginsPerSeries),
    out: flags.get('--out') ?? 'docs/EVALUATION.md',
    toStdout: flags.get('--stdout') === 'yes',
  };
}

function run(argv: readonly string[]): number {
  const options = parseArguments(argv);

  // The same dataset the seed command writes, generated by the same code, so a
  // reader can compare the report against the data the platform is showing.
  const networkOptions: NetworkOptions =
    options.profile === 'national'
      ? { ...DEMO_NETWORK_OPTIONS, coverage: 'all' }
      : DEMO_NETWORK_OPTIONS;

  const network = buildNetwork(networkOptions);
  const facilityIds = historySample(network, DEMO_HISTORY_FACILITIES_PER_REGION);
  const simulation = simulateNetwork(network, { seed: options.seed, facilityIds });

  const scored = buildScoredSeries(simulation);

  const report = runBacktest(scored.entries, {
    ...DEFAULT_BACKTEST_OPTIONS,
    horizonDays: options.horizonDays,
    strideDays: options.strideDays,
    maxOriginsPerSeries: options.origins,
  });

  // The operational question, answered by replay rather than by a second run of
  // the generator: the same days, the same lead times and the same demand, with
  // only the order quantity changed.
  const policy = comparePolicies(pairsFromSimulation(simulation));

  const command = `pnpm forecast:backtest --profile ${options.profile} --seed ${options.seed} --out ${options.out}`;
  const markdown = renderEvaluationReport(report, {
    policy,
    command,
    generatedOn: new Date().toISOString().slice(0, 10),
    seed: options.seed,
    profile: options.profile,
    scenario: simulation.scenario.id,
    dataset: {
      pairs: scored.pairs,
      unmetDays: scored.unmetDays,
      unitsWanted: scored.unitsWanted,
      unitsDispensed: scored.unitsDispensed,
    },
    cloudBackend:
      'not executed: no Google Cloud credentials or project are configured (blocker B1), so the BigQuery ML path was skipped rather than faked',
  });

  if (options.toStdout) {
    process.stdout.write(markdown);
  } else {
    writeFileSync(options.out, markdown, 'utf8');
    process.stdout.write(
      `\nWrote ${relative(process.cwd(), resolve(options.out))} in ${String(
        report.elapsedMs + policy.elapsedMs,
      )} ms\n`,
    );
    // The one line a reader wants without opening the file: the replay is a
    // counterfactual, so it is worth seeing that it reproduced the world it was
    // built from before reading anything it says about the alternatives.
    process.stdout.write(
      `Replayed ${String(policy.pairs)} of ${String(
        policy.pairsAvailable,
      )} pairs with the forecast on and off: fill rate ${policy.baseline.fillRate.toFixed(
        4,
      )} → ${policy.platform.fillRate.toFixed(4)}, unsupplied pair-days ${String(
        policy.baseline.unsuppliedDays,
      )} → ${String(policy.platform.unsuppliedDays)}, replay fidelity ${policy.fidelity.toFixed(
        3,
      )}\n`,
    );
  }

  return 0;
}

const argv = process.argv.slice(2);

if (argv.includes('--help') || argv.includes('-h')) {
  process.stdout.write(`${USAGE}\n`);
  process.exitCode = 0;
} else {
  try {
    process.exitCode = run(argv);
  } catch (error) {
    if (error instanceof UsageError) {
      process.stderr.write(`\n${error.message}\n\n${USAGE}\n`);
      process.exitCode = 2;
    } else {
      process.stderr.write(
        `\nbacktest failed: ${error instanceof Error ? error.message : String(error)}\n`,
      );
      process.exitCode = 1;
    }
  }
}
