import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

import { FEDERATION_ARCHITECTURE_REFERENCE, FEDERATION_HONESTY_BOUNDARY } from '@civora/federated';
import type { FederationOutcome, FederationPartition, FederationSweep } from '@civora/simulator';

/**
 * The ε-versus-accuracy curve, written as a document.
 *
 * The phase requires the privacy/accuracy trade-off stated honestly rather than
 * presented as free, and the honest version has to be a *number*: how much of the
 * improvement the noise removed at each target the accountant could reach, and
 * which targets it could not reach at all. So this document is generated by the
 * command that ran the sweep, and every figure in it came from a run — no cell is
 * estimated, and an unreachable target keeps the accountant's own sentence
 * instead of an accuracy figure.
 *
 * It is generated rather than hand-written for the reason `docs/EVALUATION.md`
 * and `docs/REDISTRIBUTION.md` are: a figure nobody re-derives stops matching the
 * code, and a reader cannot tell.
 *
 * The path is given without an extension by the phase's own evidence command
 * (`--out docs/federated-tradeoff`), so `.md` is appended when it is missing: a
 * Markdown document a reader cannot open as Markdown is a small avoidable tax.
 */
const markdownPath = (path: string): string => (path.endsWith('.md') ? path : `${path}.md`);

export interface FederationTradeoffInput {
  /** The command a reader types to reproduce this document. */
  readonly command: string;
  readonly generatedOn: string;
  readonly seed: string;
  readonly window: { readonly from: string; readonly to: string };
  readonly partition: FederationPartition;
  /** The run at the sweep's configured ε, with its comparisons. */
  readonly outcome: FederationOutcome;
  readonly sweep: FederationSweep;
  readonly rounds: number;
  readonly model: string;
  readonly elapsedMs: number;
}

const BACKTICK = '`';
const FENCE = BACKTICK.repeat(3);

/** An inline code span. Built rather than escaped: a nested template is a trap. */
const code = (value: string): string => `${BACKTICK}${value}${BACKTICK}`;

const count = (value: number): string => value.toLocaleString('en-IN');

const fixed = (value: number, digits = 4): string => value.toFixed(digits);

const percent = (value: number): string => `${(value * 100).toFixed(2)}%`;

const table = (header: readonly string[], rows: readonly (readonly string[])[]): string =>
  [
    `| ${header.join(' | ')} |`,
    `| ${header.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ].join('\n');

const bullets = (lines: readonly string[]): string => lines.map((line) => `- ${line}`).join('\n');

/**
 * Where the curve stops being catastrophic, computed from the sweep rather than
 * chosen. A run "beats the mean predictor" when its loss is below 1, because in
 * the shared basis the target has unit variance and `1` is what predicting the
 * pooled mean scores.
 */
export function practicalRangeSentence(sweep: FederationSweep): string {
  const reachable = sweep.points.filter((point) => point.reachable);
  if (reachable.length === 0) {
    return 'no target in this sweep was reachable by the accountant, so there is no measured range to state.';
  }
  const usable = reachable.filter((point) => (point.finalLoss ?? Infinity) < 1);
  if (usable.length === 0) {
    const best = reachable.reduce((left, right) =>
      (left.finalLoss ?? Infinity) <= (right.finalLoss ?? Infinity) ? left : right,
    );
    return `every target in this sweep left the model worse than predicting the pooled mean — the best of them, ε = ${String(
      best.epsilonTarget,
    )}, scored ${fixed(best.finalLoss ?? 0)} — so this cohort size has no usable target in the swept range.`;
  }
  const cheapest = usable.reduce((left, right) =>
    left.epsilonTarget <= right.epsilonTarget ? left : right,
  );
  const destroyed = reachable.length - usable.length;
  return `the smallest target that beat predicting the pooled mean was ε = ${String(
    cheapest.epsilonTarget,
  )} (loss ${fixed(cheapest.finalLoss ?? 0)}, explaining ${percent(
    1 - (cheapest.finalLoss ?? 0),
  )} of the demand’s variance); ${String(destroyed)} of ${String(
    reachable.length,
  )} target(s) in the swept range left the model worse than that.`;
}

/**
 * The arithmetic that sets the price, stated where the curve is read.
 *
 * The accountant's σ multiplies `clip · w_max`, and `w_max` is the largest silo's
 * share of the rows — so the cohort size, not the model, decides how much noise a
 * target ε buys. Printing the product for the partition at hand is what makes
 * "a larger cohort would need a smaller ε" a measurable claim rather than a
 * reassurance.
 */
export function noiseScaleSentence(partition: FederationPartition): string {
  const largest = partition.silos.reduce((most, silo) => Math.max(most, silo.samples.length), 0);
  const share = largest / Math.max(1, partition.samples);
  return `per-coordinate noise is σ · clip · w_max, and w_max = ${fixed(
    share,
    4,
  )} here — the largest of ${String(partition.silos.length)} silos, holding ${count(
    largest,
  )} of ${count(partition.samples)} rows. More silos means a smaller w_max, and the same ε then buys less noise.`;
}

/**
 * The curve in a sentence.
 *
 * Written around *variance explained* rather than "error removed", because the
 * interesting region of this curve is negative: at a small enough ε the noise
 * leaves the model worse than the zero model it started from, and a sentence that
 * reported "removed −8858.66% of the error" would be technically true and would
 * conceal the finding. A sweep that reached no target says so rather than being
 * summarised as though it had.
 */
function tradeoffSentence(input: FederationTradeoffInput): string {
  const quiet =
    input.sweep.quiet.initialLoss === 0
      ? 0
      : 1 - input.sweep.quiet.finalLoss / input.sweep.quiet.initialLoss;
  const opening = `In the shared basis the target has unit variance, so the zero model's loss is exactly 1 and a run's improvement is the share of the demand's variance it explained. With no mechanism at all — the same rounds over the same rows — the run explained ${percent(
    quiet,
  )} of it.`;

  const reachable = input.sweep.points.filter((point) => point.reachable);
  if (reachable.length === 0) {
    return `${opening} No target in this sweep was reachable by the accountant, so no priced run had an accuracy figure at all; the honest reading is that none of these ε values was bought.`;
  }

  // Chosen by the sweep's own figures rather than by position, so neither index
  // can be undefined and neither needs an assertion to satisfy the compiler.
  const cheapest = reachable.reduce((left, right) =>
    left.epsilonTarget <= right.epsilonTarget ? left : right,
  );
  const dearest = reachable.reduce((left, right) =>
    left.epsilonTarget >= right.epsilonTarget ? left : right,
  );
  const destroyed = reachable.filter((point) => (point.finalLoss ?? Infinity) >= 1);
  const parts = [opening];
  parts.push(
    `At ε = ${String(cheapest.epsilonTarget)} — the smallest target this sweep reached, with σ = ${fixed(
      cheapest.noiseMultiplier ?? 0,
    )} — it explained ${percent(cheapest.improvement ?? 0)}, and at ε = ${String(
      dearest.epsilonTarget,
    )} it explained ${percent(dearest.improvement ?? 0)}.`,
  );
  if (destroyed.length > 0) {
    parts.push(
      `${String(destroyed.length)} of the ${String(
        reachable.length,
      )} reachable targets left the model **worse than predicting the pooled mean** (loss above 1): at those ε values the mechanism's noise did more damage than the rounds did good.`,
    );
  }
  parts.push(
    `The gap between the run with no mechanism and the smallest target is what the privacy costs there, and it is stated rather than smoothed away.`,
  );
  return parts.join(' ');
}

export async function renderFederationTradeoff(
  path: string,
  input: FederationTradeoffInput,
): Promise<void> {
  const { partition, sweep, outcome } = input;
  const { config } = outcome.resolved;
  const run = outcome.run;
  const context = [
    `world ${partition.countryId} at ${partition.regionLevelName} level · window ${input.window.from} → ${input.window.to}`,
    `${count(partition.silos.length)} silo(s) · ${count(partition.seriesRead)} series read (${count(
      partition.seriesTooShort,
    )} too short to use) · ${count(partition.samples)} training row(s)`,
    `censored demand: ${count(partition.censoredDaysFound)} day(s) found, ${count(
      partition.censoredDaysImputed,
    )} imputed (${partition.imputations.join(', ') || 'none'}) — a stock-out is not low demand`,
    `model ${input.model} · ${count(input.rounds)} round(s) · sampling rate ${String(
      config.samplingRate,
    )} · per-sample clip ${String(config.clipNorm)} · δ ${String(config.delta)}`,
    `FedProx proximal weight μ = ${String(config.local.mu ?? 0)} · secure aggregation by additive masking: ${
      config.maskUpdates ? 'on' : 'off'
    } · seed ${input.seed}`,
    `round took ${count(Math.round(input.elapsedMs / Math.max(1, input.rounds)))} ms on average, measured by the command beside this document`,
  ];

  const sweepRows = sweep.points.map((point) => [
    String(point.epsilonTarget),
    point.noiseMultiplier === null ? '—' : fixed(point.noiseMultiplier),
    point.reachable ? 'yes' : '**no**',
    point.initialLoss === null ? '—' : fixed(point.initialLoss),
    point.finalLoss === null ? '—' : fixed(point.finalLoss),
    point.improvement === null ? '—' : percent(point.improvement),
    point.note ?? '',
  ]);

  const siloRows = outcome.perSilo.map((entry) => [
    code(entry.siloId),
    count(entry.sampleCount),
    fixed(entry.localOnlyLoss),
    fixed(entry.federatedLoss),
    `${entry.difference >= 0 ? '+' : ''}${fixed(entry.difference)}`,
    entry.federatedBetter ? 'federation lower' : 'training alone lower',
  ]);

  const totalSamples = Math.max(
    1,
    outcome.perSilo.reduce((total, entry) => total + entry.sampleCount, 0),
  );

  const lines: string[] = [
    '# Federated learning across administrative silos — the privacy/accuracy trade-off',
    '',
    `Generated ${input.generatedOn} by ${code(input.command)}. Do not edit by hand: this file is rewritten ` +
      `from the runs it describes, and an edited figure would be one nobody could reproduce.`,
    '',
    'Every number below came from a real run of the federated trainer in `packages/federated`. The',
    'silos are administrative regions of a *simulated* world; the rounds, the clipping, the masking,',
    'the noise and the accounting are the real implementation.',
    '',
    '## What was run',
    '',
    bullets(context),
    '',
    '## The trade-off',
    '',
    table(
      ['ε target', 'σ solved', 'reachable', 'initial loss', 'final loss', 'improvement', 'note'],
      sweepRows,
    ),
    '',
    tradeoffSentence(input),
    '',
    `The improvement column is ${code('1 − finalLoss / initialLoss')} in the **shared basis**, where the`,
    'target has unit variance: a loss of `1` is what a model that predicts the pooled mean scores, so',
    'the improvement is the share of the demand’s variance the run explained. It is not a percentage of',
    'anything a hospital measured — the target is recorded demand in a generated world — and it is',
    'comparable across rows because every row starts from the same zero model over the same rows.',
    '',
    `**Read the curve before quoting a figure from it.** ${practicalRangeSentence(sweep)}`,
    '',
    noiseScaleSentence(partition),
    '',
    'The multiplier σ is the accountant’s own answer: the sweep solves for the noise multiplier that',
    'spends exactly the target ε over these rounds at this sampling rate, by bisecting the accounting',
    'computation, so the ε on a row and the σ on that row cannot disagree.',
    '',
    '## FedAvg against FedProx',
    '',
  ];

  if (outcome.fedAvg === null) {
    lines.push(
      'Both were configured to the same proximal weight in this run, so the comparison was not made',
      'and no winner is claimed. Run the command without a μ override to compare them.',
      '',
    );
  } else {
    lines.push(
      table(
        ['variant', 'proximal weight μ', 'final loss', 'better'],
        [
          [
            'FedAvg',
            '0',
            fixed(outcome.fedAvg.finalLoss),
            outcome.proximalWinner === 'fedavg' ? '**yes**' : 'no',
          ],
          [
            'FedProx',
            String(config.local.mu ?? 0),
            fixed(run.finalLoss),
            outcome.proximalWinner === 'fedprox' ? '**yes**' : 'no',
          ],
        ],
      ),
      '',
      `On this partition, ${outcome.proximalWinner === 'fedavg' ? 'plain FedAvg' : 'FedProx'} reached the lower loss. Both figures are reported whichever way it falls: a proximal term that loses on a given partition is a finding about that partition, and hiding it would make the technique look like a guarantee.`,
      '',
    );
  }

  lines.push(
    '## Local-only against federated, per silo',
    '',
    'The local-only column is a model trained on that silo’s rows alone, from the same zero model,',
    'with the same epochs, batch size and optimiser — so the difference between the two columns is the',
    'federation and nothing else.',
    '',
    table(['silo', 'rows', 'local-only loss', 'federated loss', 'difference', 'verdict'], siloRows),
    '',
    `${outcome.totals.silosWhereFederationHelped} of ${String(outcome.perSilo.length)} silos ended lower under the federation; ${String(outcome.totals.silosWhereLocalWon)} ended lower trained alone. Weighted over the rows, local-only ${fixed(outcome.totals.localOnlyLoss)} against federated ${fixed(outcome.totals.federatedLoss)} (${count(totalSamples)} rows). Federation does not help everywhere, and a partition where it does not is a result rather than a failure — the cold-start path and the data-sovereignty property hold either way.`,
    '',
    '## What this document does not claim',
    '',
    bullets([
      FEDERATION_HONESTY_BOUNDARY,
      `The production substrate is cited, not built: ${FEDERATION_ARCHITECTURE_REFERENCE}.`,
      'The world, its facilities, its consumption and its stock-outs are generated. Every silo here is a simulated region, and every row of every table is simulated end to end.',
      'No figure was chosen to make the curve look better. A target the accountant could not reach is printed as unreachable with its own sentence, and a silo where federation lost is printed as a loss.',
      `The comparison tables ran with **no mechanism at all**, because they answer a different question from the curve: a silo training alone needs no privacy mechanism, so a priced federated model compared against a noise-free local one would measure the noise and call it the federation. Under DP the honest comparison is the curve above.`,
      `The privacy cost is not free and this document does not present it as free: ${practicalRangeSentence(sweep)}`,
      'That a useful ε is out of reach at six silos is a measurement about this configuration, not a defect in the mechanism. It is also why the federated-statistics path exists: sums and counts are the part that survives a small cohort, and the cold-start prior they feed is measured in the same runs.',
      'The rounds ran on one machine, partitioned by region in code. Physical separation by machine and organisation is the deployment story in the ADR, not a property of this build.',
    ]),
    '',
    '## The tests the privacy claim rests on',
    '',
    bullets([
      `${code('pnpm --filter @civora/federated test')} — the payload assertion: the real outbound payload is serialised, checked against a field allow-list **and** scanned for sentinel values planted in the silo’s raw records. It is shown to fire on a payload built to leak.`,
      `${code('packages/federated/src/accountant.test.ts')} — the accounting is checked against the published closed-form bounds of the sampled Gaussian mechanism (Mironov, Talwar & Zhang 2019, arXiv:1908.10530, Table 1).`,
      `${code('packages/federated/src/masking.test.ts')} — masking preserves the sum exactly and changes nothing an individual silo can be identified by; two assignments of the same update are indistinguishable to the coordinator.`,
      `${code('packages/federated/src/coordinator.test.ts')} — a round is a pure function of the silos, the configuration and the seed, and the noise is standardised to the clipped sensitivity.`,
    ]),
    '',
    '## Reproducing this document',
    '',
    `${FENCE}bash`,
    input.command,
    FENCE,
    '',
    `The same curve is drawn from the same code by the Federation Console, at a smaller resolution, so`,
    `the surface and this document cannot disagree about what was run.`,
    '',
  );

  const target = markdownPath(path);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, `${lines.join('\n')}\n`, 'utf8');
}
