import { z } from 'zod';

import {
  captureSourceSchema,
  clientCaptureSourceSchema,
  facilityIdSchema,
  idempotencyKeySchema,
  instantSchema,
  provenanceSchema,
  recordIdSchema,
  syntheticSchema,
} from './common';
import {
  bedStatusSchema,
  footfallObservationSchema,
  staffAttendanceSchema,
  stockLedgerEntrySchema,
  syndromicSignalSchema,
} from './sensing';

/**
 * What arrives from a facility, and what the platform records about receiving it.
 *
 * Three records belong to this boundary and nowhere else.
 *
 *  - The **request** is what a device sends. It carries the observation plus the
 *    things only the transport knows: a key that survives a retry, how the
 *    record was captured, and when the device captured it.
 *  - The **receipt** is the platform's answer to that key. It is what makes a
 *    response idempotent: a retry is answered from the receipt rather than
 *    processed again.
 *  - The **conflict** is the record of a submission that disagreed with what was
 *    already stored. It exists so that no disagreement is ever resolved
 *    silently, which is the failure a health system cannot afford.
 */

export const OBSERVATION_TYPES = [
  'stock_ledger_entry',
  'bed_status',
  'staff_attendance',
  'footfall_observation',
  'syndromic_signal',
] as const;

export const observationTypeSchema = z.enum(OBSERVATION_TYPES);
export type ObservationType = z.infer<typeof observationTypeSchema>;

/**
 * A discriminated union rather than a loose envelope with an `unknown` body, so
 * that a malformed observation is reported against the type the client declared
 * — "bedsOccupied is not a number", not "your payload is wrong".
 */
/**
 * One envelope shape per observation type.
 *
 * The type parameter keeps the literal: written as `ObservationType` it would
 * widen the discriminant to the whole union in every member, which reads as a
 * discriminated union and is not one — and the compiler would then refuse to
 * narrow a submission to the record it declares.
 */
const envelope = <K extends ObservationType, T extends z.ZodType>(type: K, observation: T) =>
  z.strictObject({
    type: z.literal(type),
    /**
     * Generated by the client, stable across retries.
     *
     * This is the whole of the idempotency contract: the same key submitted
     * twice is the same submission, and the second one is answered rather than
     * applied. A client that regenerates the key on retry is asking to be
     * treated as a new submission, and gets what it asked for.
     */
    idempotencyKey: idempotencyKeySchema,
    /**
     * How the record was captured.
     *
     * `simulation` is absent from the accepted values: a client that could label
     * its own records as generated could have them discarded as unusable, and
     * one that could label them as real could have them believed.
     */
    captureSource: clientCaptureSourceSchema,
    /**
     * When the device captured the record, which may be long before it was sent.
     * The device's clock, and therefore evidence rather than authority: the
     * server's own timestamp is what orders two submissions against each other.
     */
    capturedAt: instantSchema,
    observation,
  });

export const ingestRequestSchema = z.discriminatedUnion('type', [
  envelope('stock_ledger_entry', stockLedgerEntrySchema),
  envelope('bed_status', bedStatusSchema),
  envelope('staff_attendance', staffAttendanceSchema),
  envelope('footfall_observation', footfallObservationSchema),
  envelope('syndromic_signal', syndromicSignalSchema),
]);

export type IngestRequest = z.infer<typeof ingestRequestSchema>;

/** Any observation the boundary accepts. */
export type Observation = IngestRequest['observation'];

/** What the platform decided about a submission. */
export const INGEST_RECEIPT_OUTCOMES = ['accepted', 'duplicate', 'conflict'] as const;
export const ingestReceiptOutcomeSchema = z.enum(INGEST_RECEIPT_OUTCOMES);
export type IngestReceiptOutcome = z.infer<typeof ingestReceiptOutcomeSchema>;

/**
 * The platform's answer to one idempotency key.
 *
 * `subjectKey` is the identity of the record the submission was about, not the
 * key it arrived with, which is what lets a retry find the receipt and a
 * *different* submission find the record it disagrees with.
 */
export const ingestReceiptSchema = z.strictObject({
  idempotencyKey: idempotencyKeySchema,
  type: observationTypeSchema,
  facilityId: facilityIdSchema,
  subjectKey: z.string().trim().min(1),
  outcome: ingestReceiptOutcomeSchema,
  /**
   * The moment the server processed the submission.
   *
   * Authoritative over every device clock, and the only timestamp a conflict is
   * decided by. A device that has been offline for a week reports what it saw a
   * week ago; that is worth recording and not worth trusting for ordering.
   */
  receivedAt: instantSchema,
  captureSource: captureSourceSchema,
  synthetic: syntheticSchema,
  provenance: provenanceSchema,
});

export type IngestReceipt = z.infer<typeof ingestReceiptSchema>;

/**
 * The rules the platform has for a disagreement.
 *
 * Exactly one today, declared as an enum so that every conflict record states
 * which rule decided it and a second rule can be added without making the older
 * records ambiguous.
 */
export const SYNC_CONFLICT_RESOLUTIONS = ['stored-record-wins'] as const;
export const syncConflictResolutionSchema = z.enum(SYNC_CONFLICT_RESOLUTIONS);
export type SyncConflictResolution = z.infer<typeof syncConflictResolutionSchema>;

/** One field the two submissions disagree about, with both values as stored. */
export const fieldDifferenceSchema = z.strictObject({
  field: z.string().trim().min(1),
  stored: z.string(),
  submitted: z.string(),
});

export type FieldDifference = z.infer<typeof fieldDifferenceSchema>;

/**
 * Two submissions claiming the same observation with different contents.
 *
 * Recorded rather than resolved silently, and recorded *per field* so that a
 * reader can see what actually differed instead of being told that something
 * did. The losing submission is kept in full in the differences, because the
 * thing a supervisor needs to judge is what the facility typed, not that it
 * disagreed.
 */
export const syncConflictSchema = z
  .strictObject({
    id: recordIdSchema,
    type: observationTypeSchema,
    facilityId: facilityIdSchema,
    subjectKey: z.string().trim().min(1),
    /** The key of the submission that was already stored. */
    storedIdempotencyKey: idempotencyKeySchema,
    /** The key of the submission that was refused. */
    submittedIdempotencyKey: idempotencyKeySchema,
    /** Never empty: a conflict with nothing to report is not a conflict. */
    differences: z.array(fieldDifferenceSchema).min(1),
    resolution: syncConflictResolutionSchema,
    /** Why this rule applied, so a reader does not have to infer it. */
    reason: z.string().trim().min(1),
    detectedAt: instantSchema,
    synthetic: syntheticSchema,
    provenance: provenanceSchema,
  })
  .refine((conflict) => conflict.storedIdempotencyKey !== conflict.submittedIdempotencyKey, {
    message: 'two submissions under the same idempotency key are a replay, not a conflict',
    path: ['submittedIdempotencyKey'],
  });

export type SyncConflict = z.infer<typeof syncConflictSchema>;
