import { CivoraError, eachDay } from '@civora/domain';
import type {
  BedStatus,
  DateOnly,
  District,
  FacilityId,
  FootfallObservation,
  Item,
  Region,
  StaffAttendance,
  StockLedgerEntry,
  SyndromicSignal,
} from '@civora/domain';

import { itemsForTier } from './anchors/catalogue';
import { simulateFacilityBehaviour } from './behaviour';
import type { DemandShortfall, OfflineSpan, SimulatedOrder } from './behaviour';
import type { Network } from './network';
import { DEFAULT_SCENARIO_ID, HISTORY_FROM, SIMULATION_END, requireScenario } from './scenarios';
import type { ScenarioSpec } from './scenarios';

/**
 * The whole generated country, in one call.
 *
 * This is the boundary the rest of the platform crosses: everything behind it —
 * the network, the catalogue, the consumption model — is an implementation
 * detail, and what comes out is a set of observations in the domain's own
 * shapes, each one carrying the scenario and the seed that produced it, so any
 * figure in a demonstration can be regenerated by anyone who has those two
 * things.
 *
 * Two decisions worth knowing before reading further:
 *
 *  - **The network and the history have different sizes.** A national network of
 *    facilities is cheap to state and expensive to simulate, so coverage of the
 *    country and depth of history are separate choices. `facilityIds` selects
 *    which facilities get a simulated past; the rest exist administratively.
 *  - **Only the facilities a scenario targets are perturbed.** Everything else
 *    in the same run behaves ordinarily, which is what makes the scenario an
 *    experiment: an effect is only an effect if there is something to compare
 *    it against.
 */

export interface SimulationOptions {
  readonly seed: string;
  /** Scenario to perturb the world with. Defaults to the monsoon surge. */
  readonly scenarioId?: string;
  /** First day of the history, inclusive. Defaults to the earliest scenario window. */
  readonly from?: DateOnly;
  /** Last day of the history, inclusive. Defaults to the date the simulation ends. */
  readonly to?: DateOnly;
  /** Facilities to generate a history for. Defaults to every facility in the network. */
  readonly facilityIds?: readonly FacilityId[];
}

/** What a facility told the network, and when it went quiet. */
export interface FacilityReporting {
  /** Days on which anything at all reached the network. */
  readonly reportedDays: readonly DateOnly[];
  /**
   * Spells during which nothing did.
   *
   * Held apart from the observations because the observations for those days
   * exist: they were captured locally and delivered on reconnection. What the
   * span records is that the network heard nothing at the time, which is what
   * makes a position stale — and the difference between the two is the whole
   * reason the platform treats a stale reading as unknown rather than as zero.
   */
  readonly offlineSpans: readonly OfflineSpan[];
}

export interface SimulationCounts {
  readonly facilities: number;
  readonly days: number;
  readonly itemHistories: number;
  readonly ledgerEntries: number;
  readonly syndromicSignals: number;
  readonly bedStatuses: number;
  readonly staffAttendance: number;
  readonly footfall: number;
  readonly shortfalls: number;
  readonly orders: number;
}

export interface Simulation {
  readonly seed: string;
  readonly scenario: ScenarioSpec;
  readonly from: DateOnly;
  readonly to: DateOnly;
  readonly ledgerEntries: readonly StockLedgerEntry[];
  readonly syndromicSignals: readonly SyndromicSignal[];
  readonly bedStatuses: readonly BedStatus[];
  readonly staffAttendance: readonly StaffAttendance[];
  readonly footfall: readonly FootfallObservation[];
  /** Demand no facility could meet. The platform cannot observe this. */
  readonly shortfalls: readonly DemandShortfall[];
  readonly orders: readonly SimulatedOrder[];
  readonly reporting: ReadonlyMap<FacilityId, FacilityReporting>;
  readonly counts: SimulationCounts;
}

/** The window a generated history has to cover to exercise every scenario. */
export const scenarioCoverWindow = (): { readonly from: DateOnly; readonly to: DateOnly } => ({
  from: HISTORY_FROM,
  to: SIMULATION_END,
});

export function simulateNetwork(network: Network, options: SimulationOptions): Simulation {
  const scenario = requireScenario(options.scenarioId ?? DEFAULT_SCENARIO_ID);
  const from = options.from ?? HISTORY_FROM;
  const to = options.to ?? SIMULATION_END;

  if (to < from) {
    throw new CivoraError(`a simulated history cannot end (${to}) before it begins (${from})`);
  }

  const days = eachDay(from, to);
  const districtById: ReadonlyMap<string, District> = new Map(
    network.districts.map((district) => [district.id, district]),
  );
  const regionById: ReadonlyMap<string, Region> = new Map(
    network.regions.map((region) => [region.id, region]),
  );

  const requested = options.facilityIds;
  const selected =
    requested === undefined
      ? network.facilities
      : network.facilities.filter((facility) => requested.includes(facility.id));

  if (requested !== undefined && selected.length !== requested.length) {
    const known = new Set(network.facilities.map((facility) => facility.id as string));
    const missing = requested.filter((id) => !known.has(id));
    throw new CivoraError(
      `asked to simulate ${String(missing.length)} facilities that are not in this network: ${missing.join(', ')}`,
    );
  }

  const ledgerEntries: StockLedgerEntry[] = [];
  const syndromicSignals: SyndromicSignal[] = [];
  const bedStatuses: BedStatus[] = [];
  const staffAttendance: StaffAttendance[] = [];
  const footfall: FootfallObservation[] = [];
  const shortfalls: DemandShortfall[] = [];
  const orders: SimulatedOrder[] = [];
  const reporting = new Map<FacilityId, FacilityReporting>();

  // Tier stock lists are identical for every facility of a tier, so they are
  // built once. The cold-chain variant matters because a facility without a
  // working refrigerator is not sent a vaccine it cannot keep.
  const itemLists = new Map<string, readonly Item[]>();

  for (const facility of selected) {
    const district = districtById.get(facility.districtId);
    const region = regionById.get(facility.regionId);
    if (district === undefined || region === undefined) {
      throw new CivoraError(
        `facility ${facility.id} refers to a district or region that is not in this network`,
      );
    }

    const listKey = `${facility.tier}:${facility.coldChain.available ? 'cold' : 'ambient'}`;
    let items = itemLists.get(listKey);
    if (items === undefined) {
      items = itemsForTier(facility.tier).filter(
        (item) => !item.coldChain || facility.coldChain.available,
      );
      itemLists.set(listKey, items);
    }

    const behaviour = simulateFacilityBehaviour({
      facility,
      district,
      region,
      scenario,
      items,
      days,
      seed: options.seed,
    });

    ledgerEntries.push(...behaviour.ledgerEntries);
    syndromicSignals.push(...behaviour.syndromicSignals);
    bedStatuses.push(...behaviour.bedStatuses);
    staffAttendance.push(...behaviour.staffAttendance);
    footfall.push(...behaviour.footfall);
    shortfalls.push(...behaviour.shortfalls);
    orders.push(...behaviour.orders);
    reporting.set(facility.id, {
      reportedDays: behaviour.reportedDays,
      offlineSpans: behaviour.offlineSpans,
    });
  }

  const itemHistories = selected.reduce((total, facility) => {
    const listKey = `${facility.tier}:${facility.coldChain.available ? 'cold' : 'ambient'}`;
    return total + (itemLists.get(listKey)?.length ?? 0);
  }, 0);

  return {
    seed: options.seed,
    scenario,
    from,
    to,
    ledgerEntries,
    syndromicSignals,
    bedStatuses,
    staffAttendance,
    footfall,
    shortfalls,
    orders,
    reporting,
    counts: {
      facilities: selected.length,
      days: days.length,
      itemHistories,
      ledgerEntries: ledgerEntries.length,
      syndromicSignals: syndromicSignals.length,
      bedStatuses: bedStatuses.length,
      staffAttendance: staffAttendance.length,
      footfall: footfall.length,
      shortfalls: shortfalls.length,
      orders: orders.length,
    },
  };
}
