import { AuthProviderError } from '../errors';
import type { AuthProvider, Credentials, Principal } from '../ports/auth-provider';

/**
 * Simulated identities used by the offline platform and the test suite.
 *
 * These addresses are not real and the scope identifiers are placeholders; the
 * administrative spine they refer to is generated by the simulator. The point
 * of the adapter is that role and scope are resolved server-side through the
 * same port a real identity provider will use.
 */
export const FIXTURE_ACCOUNTS: Readonly<Record<string, Principal>> = {
  'nurse@phc.example': {
    uid: 'fixture-phc-staff',
    displayName: 'PHC staff (simulated)',
    role: 'phc_staff',
    scope: {
      stateId: 'state-demo-01',
      districtId: 'district-demo-001',
      facilityId: 'facility-demo-0001',
    },
  },
  'officer@district.example': {
    uid: 'fixture-district-officer',
    displayName: 'District officer (simulated)',
    role: 'district_officer',
    scope: {
      stateId: 'state-demo-01',
      districtId: 'district-demo-001',
    },
  },
  'controller@state.example': {
    uid: 'fixture-state-officer',
    displayName: 'State officer (simulated)',
    role: 'state_officer',
    scope: {
      stateId: 'state-demo-01',
    },
  },
};

/**
 * An `AuthProvider` that resolves identities from a fixed table.
 *
 * It performs no credential verification: any non-empty password is accepted
 * for a known fixture address. It exists so that the offline platform has an
 * identity to work with, and it must never be selected where real identities or
 * real data are involved.
 */
export class FixtureAuthProvider implements AuthProvider {
  readonly kind = 'fixture';
  readonly #accounts: Readonly<Record<string, Principal>>;
  #principal: Principal | null = null;

  constructor(accounts: Readonly<Record<string, Principal>> = FIXTURE_ACCOUNTS) {
    this.#accounts = accounts;
  }

  async currentPrincipal(): Promise<Principal | null> {
    return this.#principal;
  }

  async signIn(credentials: Credentials): Promise<Principal> {
    const email = credentials.email.trim().toLowerCase();
    const principal = this.#accounts[email];

    if (principal === undefined) {
      throw new AuthProviderError(`no fixture identity is registered for "${email}"`);
    }
    if (credentials.password.trim() === '') {
      throw new AuthProviderError('a password is required, even for a simulated identity');
    }

    this.#principal = principal;
    return principal;
  }

  async signOut(): Promise<void> {
    this.#principal = null;
  }
}
