/**
 * What on these surfaces is real, and what is generated.
 *
 * The demo's most dangerous reading is not a wrong figure, it is a right figure
 * taken for a real one. So the platform answers the question once, in one place,
 * and every command surface can point at it: which layers were **retrieved from
 * published sources**, which are **simulated from those anchors plus documented
 * assumptions**, and under which seed.
 *
 * The lists are deliberately short and concrete rather than reassuring. "All
 * data is simulated" is true and useless; a judge, or a ministry officer, needs
 * to know that the district populations and the medicine list are real published
 * values while the stock, the consumption and the outbreaks are generated — and
 * that every generated record carries `synthetic: true` so a surface that showed
 * one as a measurement would be caught by the test suite.
 *
 * The assumptions themselves are not restated here. They live, with their
 * sources, licences and retrieval dates, in `docs/DATA_PROVENANCE.md`, and this
 * file names that document rather than paraphrasing it — a second copy of a real
 * table is a second table that can drift.
 */

/** Where the full table lives, named on every surface that shows a figure. */
export const PROVENANCE_DOCUMENT = 'docs/DATA_PROVENANCE.md';

export interface ProvenanceLayer {
  readonly layer: string;
  readonly detail: string;
  /** Where the values came from, for a reader who wants to check them. */
  readonly source: string;
}

/** Layers retrieved from published sources and used verbatim or by rule. */
export const REAL_LAYERS: readonly ProvenanceLayer[] = [
  {
    layer: 'Administrative geography',
    detail:
      'States, districts, blocks and the facility sites derived from them. District and state populations are the Census of India 2011 figures, used as the demand denominator.',
    source: 'Census of India 2011 district and state listings',
  },
  {
    layer: 'Medicine catalogue',
    detail:
      'Seventy items with their dosage forms, strengths, levels of care and surge sensitivity, carried into the catalogue by the importer that would read a real extract.',
    source: 'National List of Essential Medicines 2022, CDSCO',
  },
  {
    layer: 'Facility norms',
    detail:
      'Catchment populations by tier and the bed and staffing norms facilities are sited against.',
    source: 'Indian Public Health Standards, MoHFW',
  },
];

/** Layers generated from those anchors, plus the assumptions in the table. */
export const SIMULATED_LAYERS: readonly ProvenanceLayer[] = [
  {
    layer: 'Facility network',
    detail:
      'Which facilities exist, their identifiers, coordinates, connectivity and cold-chain availability. Identifiers are prefixed SIM- and no identifier claims to be an official code.',
    source: 'Generated from population and the IPHS norms',
  },
  {
    layer: 'Stock, consumption and ordering',
    detail:
      'Every ledger entry, batch, expiry, cover figure and demand rate. No stock position shown anywhere on this platform came from a real store.',
    source: 'Generated by the simulator from the anchors and its assumptions',
  },
  {
    layer: 'Beds, attendance and footfall',
    detail: 'Occupancy, posts filled and presentations, at the observed rates in the table.',
    source: 'Generated by the simulator',
  },
  {
    layer: 'Disease events and risk scores',
    detail:
      'Syndromic signals and outbreaks. The syndrome list is a plausible clinical grouping rather than a published taxonomy, and the scoring methods that read them are real implementations over generated data.',
    source: 'Generated; methods are the platform’s own',
  },
  {
    layer: 'Forecasts, alerts, plans and federated rounds',
    detail:
      'Derived from the generated records by the platform’s own code. The methods are real; the data they ran on is not real health data.',
    source: 'Computed per read, from the layers above',
  },
];

export interface ProvenanceView {
  readonly seed: string;
  readonly fingerprint: string;
  readonly scenarioId: string;
  readonly scenarioLabel: string;
  readonly window: { readonly from: string; readonly to: string; readonly days: number };
  readonly document: string;
  readonly realLayers: readonly ProvenanceLayer[];
  readonly simulatedLayers: readonly ProvenanceLayer[];
}

/** The panel's content, from the store's own facts rather than a constant here. */
export function provenanceFor(info: {
  readonly seed: string;
  readonly fingerprint: string;
  readonly scenarioId: string;
  readonly scenarioLabel: string;
  readonly window: { readonly from: string; readonly to: string; readonly days: number };
}): ProvenanceView {
  return {
    seed: info.seed,
    fingerprint: info.fingerprint,
    scenarioId: info.scenarioId,
    scenarioLabel: info.scenarioLabel,
    window: info.window,
    document: PROVENANCE_DOCUMENT,
    realLayers: REAL_LAYERS,
    simulatedLayers: SIMULATED_LAYERS,
  };
}
